##Write a program to store the below details with separate variables (name, age, dob, height, weight, degree, gender, is_alive). Set the values with appropriate types based on the value. Say age should be an integer, etc.,
name=input("ENTER YOUR NAME:")
age=int(input("ENTER YOUR AGE:"))
dob=input("ENTER YOUR DATE OF BRITH:")
height=input("ENTER YOUR HEIGHT:")
weight=int(input("ENTER YOUR WEIGHT:"))
degree=input("ENTER YOUR DEGREE:")
gender=input("ENTER YOUR GENDER:")
is_alive=True
print("YOUR NAME IS",name)
print("YOUR AGE IS",age)
print("YOUR DATE OF BRITH IS",dob)
print("YOUR HEIGHT IS",height)
print("YOUR WEIGHT IS",weight)
print("YOUR DEGREE IS",degree)
print("YOUR GENDER IS",gender)
print("IS ALIVE IS",is_alive)